spring:
  kafka:
    consumer:
      group-id: app.1
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      primary: mongodb://localhost:27017/ca
      secondary: mongodb://localhost:27017/us